version: '3'
services:
  web:
    build: .
    environment:
      DB_HOST: "db"
      DB_NAME: "app"
      DB_USER: "app"
      DB_PASSWORD: "app"
    volumes:
      - /var/www/neos/Data
    ports:
      - "8080:80"
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: "2142c00050d5"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "app"
    volumes:
      - /var/lib/mysql
    ports:
      - "33060:3306"
