Neos:
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        host: '%env:DB_HOST%'
        dbname: '%env:DB_NAME%'
        user: '%env:DB_USER%'
        password: '%env:DB_PASSWORD%'
  GoogleAnalytics:
    authentication:
      applicationName: 'Neos Google Analytics'
      # clientId:
      # clientSecret:
      # developerKey:
