Neos:
  ContentRepository:
    contentDimensions:
      language:
        label: Language
        icon: icon-language
        default: de
        defaultPreset: de
        presets:
          de:
            label: Deutsch
            values:
              - de
            uriSegment: de
          en:
            label: English
            values:
              - en
            uriSegment: en  
  Neos:
    userInterface:
      navigateComponent:
        structureTree:
          # HACK: Workaround deeply nested node not being selected in context structure.
          # This is related to Dynatree not knowing about the node in question when it is selected
          # in backend view of site.
          loadingDepth: 6
